### PR TITLE
Feat Dynamic Icon component

### PR DESCRIPTION
**Pull request by Remeic**
## Goal

Allow user to dynamically render icon based on name

### Description
The 'Icon' component allows you to render one of the available icons by specifying its name using the __as__ property. Additionally, the component accepts all props normally accepted by icons.

Usage:
```typescript
<Icon as="Iconoir" height={36} width={36} />
```

## Additional Notes

1. To avoid critical runtime errors, a check is performed on the IconComponent derived from name.

```typescript
 const IconComponent = icons[as] as React.ComponentType<
    Omit<IconProps<T>, "as">
  >;

  if(!IconComponent){ 
    return null;
  }
```

2. I have placed all the icon exports inside the _icons.ts_ file to avoid circular dependencies once the _Icon.tsx_ component is exported. 
i would have liked all the icons to be inside an 'icons' folder, but such a change would have changed completely the folder structure.

3. I had to include @typescript-eslint, even though I didn't want to, to solve the 'Unexpected token' error on the type declaration at the beginning of 'Icon.tsx'.

## Video
Iconoir_Dynamic_Icon_Component_PR

I hope I have submitted the PR correctly. I remain available to make any required changes.

### CODE REVIEW

**Comment by its-monotype** [comment]
By the way, the most important thing here is to export everything correctly so as not to ruin performance, I don’t really an expert in this, but for example, if the mui icons not imported as default improt, then there will be a deterioration in test performance, etc.

**Comment by sammarks** [comment]
I am worried about that as well; my theory is as long as you don't import the `Icon` component, then Webpack et al should tree-shake and not include the entire pack. But once you include the `Icon` component, the entire pack is added.

**It's probably worth discussing if we want to include this "shortcut" in the package at all,** as it could encourage practices that end up loading the entire icon pack with your bundle. The alternative is also relatively simple, to just `import * as Icons from 'iconoir-react'` and then create a component however you please to render icons by their name.

Maybe that's something we could just document instead as an example.

**Comment by Remeic** [comment]
Hi @sammarks 
Thanks for suggestions!

Changes:

1. Delete eslint typescript dependency and config file
2. Delete package lock file
3. Add @typescript-eslint/parser dependency on the root, to solve ts issue reported previously
4. Add plugin:@typescript-eslint/recommended inside eslint.cjs
5. Removed icons.ts file
6. Add Icon.tsx inside build script
7. Add `export { Icon } from './Icon'` on template
8. Change Icon.tsx internal type to omit not icons file
9. Add 'Icon.tsx' component inside react-native because i notice that build script add export on 'index' even. in the native part

I remain available for any requested modifications. I hope I have resolved all the issues, and I apologize for any oversights.

**Comment by sammarks** [comment]
@Remeic I apologize for wasting your time with the review round, but I don't think we're going to accept this PR. Importing all of the icons and using a generic `<Icon />` component instead of using the icons individually is a dangerous practice when it comes to bundle size, and we don't want to have official support for something that could make your bundle size balloon.

The alternative (and we can document this) is to just import all of the icons using `import * as Icons from 'iconoir-react'`, filter out the context component, and then you should have an object where the key is the name of the icon and the value is the icon component itself.

So if you wanted to implement a random icon viewer, that's the way you would go about it, and then just choose a key at random and render that icon.

If you wanted to implement an icon selector, you would also have to import all of the icons, and then you could just render a select list using the icon names and the rendered icons.

**Comment by Remeic** [comment]
Hi @sammarks 
No problem, I created the PR after this answer from Luca.
https://twitter.com/GiulioFagioli/status/1654539997574250497?cxt=HHwWgoC24ZLXjfYtAAAA

I needed to render a specific icon given the name, I'll look for another solution.

Thank you

**Pull request closed without merging**
