### PR TITLE
feat: support multiple keywords in search

### LINKED ISSUE #264: Search on website limited to a single word
## Step to reproduce

Search on iconoir.com for keywords such as `no access` or `add folder`

### Actual behavior
It's not possible to search for more than 1 word. It's way more difficult to find the right icons for your query. Can we support multiple words? Wdyt? @sammarks 

(Ps. The issue is present in the live version, but we could wait until we release the branch for the new website and then optimize the search.)

### PR DESCRIPTION
**Pull request by paescuj**
Fixes #264 

- [ ] ~Clean-up~
- [ ] ~Add debounce~

### CODE REVIEW

**Review by sammarks — APPROVED** [review]
LGTM as-is. We don't need a debounce for the search; we use React 18 and startTransition, which means results render as quickly as the browser can without interrupting the main thread (and making input updates slow). That negates the need for a debounce.

**Comment by lucaburgio** [comment]
Shall we go ahead with this as-is then? @sammarks @paescuj

**Comment by sammarks** [comment]
Sounds good to me!

**Comment by paescuj** [comment]
> LGTM as-is. We don't need a debounce for the search; we use React 18 and startTransition, which means results render as quickly as the browser can without interrupting the main thread (and making input updates slow). That negates the need for a debounce.

You're right! Somehow had the feeling that the page slowed down when typing fast during a quick test last time, but this doesn't seem to be the case 👍

**Pull request merged**
