### PR TITLE
feat: naming convention

### PR DESCRIPTION
**Pull request by lucaburgio**
Ref thread: #251 

Changes:

Other

`bookmark-empty` to `bookmark`
`divide-selection-1` to `split-area`
`cloud-book-alt` to `cloud-bookmark`
`privacy policy` to `privacy-policy` 
`save-floppy-disk` to `floppy-disk`
`load-action-floppy` to `floppy-disk-arrow-out`
`save-action-floppy` to `floppy-disk-arrow-in`
`mail-opened` to `mail-open`
`pin-alt` to `map-pin`
`shopping-bag-alt` to `shopping-bag-pocket`
`key-alt-back` to `key-back`
`key-alt-minus` to `key-minus`
`key-alt-plus` to `key-plus`
`key-alt-remove` to `key-xmark`
`key-alt` to `key`

No access

`card-issue` to `card-no-access`
`no-access-window` to `window-no-access`
`log-denied` to `log-no-access`

Warning

`folder-alert` to `folder-warning`
`wifi-issue` to `wifi-warning`
`laptop-issue` to `laptop-warning`
`tv-issue` to `tv-warning`
`domotic-issue` to `domotic-warning`
`headset-issue` to `headset-warning`
`shopping-bag-issue` to `shopping-bag-warning`

Lock

`card-locked` to `card-lock`
`locked-book` to `book-lock`
`locked-window` to `window-lock`
`lock-key` to `lock-square`

Circle

`coin` to `dollar-circle`
`hospital-sign` to `hospital-circle`
`info-empty` to `info-circle`
`refresh-circular` to `refresh-circle`

Shield

`card-security` to `card-shield`

Check

`check-window` to `window-check`
`voice-ok` to `voice-check`
`password-pass` to `password-check`
`clean-water` to `water-check`

Droplet

`gas-tank-drop` to `gas-tank-droplet`

Square

`settings-cloud` to `cloud-square`
`text-alt` to `text-square`
`cooling` to `cooling-square`
`selection` to `square-dashed`
`git-command` to `slash-square`
`divide-selection-2` to `split-square-dashed`
`fast-arrow-down-box` to `fast-arrow-down-square`
`fast-arrow-left-box` to `fast-arrow-left-square`
`fast-arrow-right-box` to `fast-arrow-right-square`
`fast-arrow-up-box` to `fast-arrow-up-square`
`heating` to `heating-square`
`carbon` to `c-square`
`fluorine` to `f-square`
`hydrogen` to `h-square`
`nitrogen` to `n-square`
`oxygen` to `o-square`
`x-coordinate` to `x-square`
`y-coordinate` to `y-square`
`z-coordinate` to `z-square`

Tag

`ar-symbol` to `ar-tag`
`vr-symbol` to `vr-tag`
`ip-address` to `ip-address-tag`
`closed-captions` to `closed-captions-tag`
`pharmacy-cross-square` to `pharmacy-cross-tag`
`down-round-arrow` to `arrow-down-tag`
`enlarge-round-arrow` to `arrow-enlarge-tag`
`left-round-arrow` to `arrow-left-tag`
`reduce-round-arrow` to `arrow-reduce-tag`
`right-round-arrow` to `arrow-right-tag`
`up-round-arrow` to `arrow-up-tag`

X Mark

`grid-remove` to `grid-xmark`
`remove-pin-alt` to `map-pin-xmark`
`remove-media-video` to `media-video-xmark`
`remove-media-image` to `media-image-xmark`
`remove-user` to `user-xmark`
`remove-square` to `xmark-square`
`multiple-pages-delete` to `multiple-pages-xmark`
`phone-delete` to `phone-xmark`
`delete-circle` to `xmark-circle`
`cancel` to `xmark`
`shield-cross` to `shield-xmark`
`map-issue` to `map-xmark`
`maps-arrow-issue` to `maps-arrow-xmark`
`cloud-error` to `cloud-xmark`
`bubble-error` to `bubble-xmark`
`chat-bubble-error` to `chat-bubble-xmark`
`wifi-error` to `wifi-xmark`
`fingerprint-error-circle` to `fingerprint-xmark-circle`
`voice-error` to `voice-xmark`
`password-error` to `password-xmark`
`shopping-code-error` to `shopping-code-xmark`
`error-window` to `window-xmark`
`drone-error` to `drone-xmark`
`ev-plug-error` to `ev-plug-xmark`
`web-window-close` to `web-window-xmark`

Minus

`remove-folder` to `folder-minus`
`remove-database-script` to `database-script-minus`
`remove-frame` to `frame-minus-in`
`ruler-remove` to `ruler-minus`
`remove-from-cart` to `cart-minus`
`remove-selection` to `minus-square-dashed`
`minus-pin-alt` to `map-pin-minus`
`shopping-bag-remove` to `shopping-bag-minus`
`multiple-pages-remove` to `multiple-pages-minus`

Green

`green-bus` to `bus-green`
`green-truck` to `truck-green`
`green-vehicle` to `vehicle-green`

Plus

`add-circle` to `plus-circle`
`add-square` to `plus-square`
`add-keyframe-alt` to `keyframe-plus-in`
`add-keyframe` to `keyframe-plus`
`add-keyframes` to `keyframes-plus`
`add-circle` to `plus-circle`
`add-square` to `plus-square`
`add-keyframe-alt` to `keyframe-plus-in`
`add-keyframe` to `keyframe-plus`
`add-keyframes` to `keyframes-plus`
`mic-add` to `microphone-plus`
`chat-add` to `chat-plus-in`
`phone-add` to `phone-plus`
`add-database-script` to `database-script-plus`
`add-frame` to `frame-plus-in`
`add-lens` to `lens-plus`
`ruler-add` to `ruler-plus`
`add-folder` to `folder-plus`
`add-page` to `page-plus-in`
`multiple-pages-add` to `multiple-pages-plus`
`add-page-alt` to `page-plus`
`grid-add` to `grid-plus`
`music-double-note-add` to `music-double-note-plus`
`music-note-add` to `music-note-plus`
`playlist-add` to `playlist-plus`
`add-selection` to `plus-square-dashed`
`add-media-image` to `media-image-plus`
`add-media-video` to `media-video-plus`
`shield-add` to `shield-plus-in`
`add-hexagon` to `hexagon-plus`
`add-to-cart` to `cart-plus`
`shopping-bag-add` to `shopping-bag-plus`
`bin-add` to `bin-plus`
`add-user` to `user-plus`
`add-pin-alt` to `map-pin-plus`

### CODE REVIEW

**Comment by lucaburgio** [comment]
Additional changes:

`mic-remove` to `microphone-minus`
`mic-check` to `microphone-check`
`mic` to `microphone`
`mic-speaking` to `microphone-speaking`
`mic-warning` to `microphone-warning`
`mic-mute` to `microphone-mute`
`db-error` to `db-xmark`
`move-ruler` to `ruler-arrows`
`move-down` to `dot-arrow-down`
`move-up` to `dot-arrow-up`
`move-right` to `dot-arrow-down`
`move-left` to `dot-arrow-left`
`3d-select-solid` to `cube`
`cut-solid-with-curve` to `cube-cut-with-curve`
`bin-minus` to `bin-minus-in`
`bin-plus` to `bin-plus-in`
`3d-add-hole` to `cube-hole`
`patch-holes-3d` to `cube-bandage`
`search-font` to `text-magnifying-glass`
`missing-font` to `font-question`
`font-size` to `text-arrows-up-down`

**Comment by lucaburgio** [comment]
Additional changes:

`arrow-bl-circle` to `arrow-down-left-circle`
`arrow-bl-square` to `arrow-down-left-square`
`arrow-br-circle` to `arrow-down-right-circle`
`arrow-br-square` to `arrow-down-right-square`
`arrow-tl-circle` to `arrow-top-left-circle`
`arrow-tl-square` to `arrow-top-left-square`
`arrow-tr-circle` to `arrow-top-right-circle`
`arrow-tr-square` to `arrow-top-right-square`
`arrow-bl` to `arrow-down-left`
`arrow-br` to `arrow-down-right`
`arrow-tl` to `arrow-top-left`
`arrow-tr` to `arrow-top-right`
`network-alt` to `network-reverse`
`voice-phone` to `mobile-voice`
`fingerprint-phone` to `mobile-fingerprint`
`dev-mode-phone` to `mobile-dev-mode`
`dev-mode-laptop` to `laptop-dev-mode`
`db-check` to `database-check`
`db-search` to `database-search`
`db-warning` to `database-warning`
`db` to `database`

**Comment by lucaburgio** [comment]
Additional changes:

removed `eye-empty`
removed `eye-off`

`eye-alt` to `eye`
`eye-close` to `eye-closed`

**Comment by lucaburgio** [comment]
@sammarks @DaniFoldi take a look to see if everything looks good to you. When approved, I'll prepare the merge and the release 🙏🏻🔥

**Comment by lucaburgio** [comment]
Additional changes:

`clutery` to `cutlery`

**Comment by lucaburgio** [comment]
Additional changes:

`remove-keyframe-alt` to `keyframe-minus-in`
`remove-keyframe` to `keyframe-minus`
`remove-keyframes` to `keyframes-minus`
`chat-remove` to `chat-minus-in`
`phone-remove` to `phone-minus`
`remove-page` to `page-minus-in`
`remove-page-alt` to `page-minus`
`remove-pin` to `pin-slash`
`remove-link` to `link-slash`

**Comment by lucaburgio** [comment]
hexagon

Additional changes:

Removed:

`apple-half-alt`
`basketball`
`hexagon-alt`
`printer`
`cut-alt`

Renamed:

`basketball-alt` to `basketball`
`printer-alt` to `printer`
`doc-star-alt` to `doc-star-in`
`doc-search-alt` to `doc-magnifying-glass-in`
`doc-search` to `doc-magnifying-glass`

**Comment by lucaburgio** [comment]
Additional changes:

`water-check` to `droplet-check`
`no-link` to `link-xmark`
`no-lock` to `lock-slash`
`no-battery` to `battery-slash`
`no-coin` to `coin-slash`
`no-credit-card` to `credit-card-slash`
`no-smoking` to `cigarette-slash`
`arrow-top-left-circle` to `arrow-up-left-circle`
`arrow-top-left-square` to `arrow-up-left-square`
`arrow-top-right-circle` to `arrow-up-right-circle`
`arrow-top-right-square` to `arrow-up-right-square`
`arrow-top-left` to `arrow-up-left`
`arrow-top-right` to `arrow-up-right`
`headset-charge` to `headset-bolt`

**Comment by lucaburgio** [comment]
Additional changes:

Removed:

`color-picker-empty`

Renamed:

`shortcut` to `shortcut-square`

**Comment by lucaburgio** [comment]
Added 149 new icons: First SOLID ones.

`1st-medal-solid.svg`
`adobe-after-effects-solid.svg`
`adobe-illustrator-solid.svg`
`adobe-indesign-solid.svg`
`adobe-lightroom-solid.svg`
`adobe-photoshop-solid.svg`
`adobe-xd-solid.svg`
`airplay-solid.svg`
`alarm-solid.svg`
`align-bottom-box-solid.svg`
`align-horizontal-centers-solid.svg`
`align-horizontal-spacing-solid.svg`
`align-left-box-solid.svg`
`align-right-box-solid.svg`
`align-top-box-solid.svg`
`align-vertical-centers-solid.svg`
`align-vertical-spacing-solid.svg`
`app-store-solid.svg`
`apple-shortcuts-solid.svg`
`arrow-down-circle-solid.svg`
`arrow-down-left-circle-solid.svg`
`arrow-down-right-circle-solid.svg`
`arrow-down-right-square-solid.svg`
`arrow-left-circle-solid.svg`
`arrow-right-circle-solid.svg`
`arrow-up-circle-solid.svg`
`arrow-up-left-circle-solid.svg`
`arrow-up-left-square-solid.svg`
`arrow-up-right-circle-solid.svg`
`arrow-up-right-square-solid.svg`
`bathroom-solid.svg`
`bitcoin-circle-solid.svg`
`bluetooth-tag-solid.svg`
`bold-square-solid.svg`
`book-solid.svg`
`bookmark-circle-solid.svg`
`bookmark-solid.svg`
`bubble-search-solid.svg`
`cable-tag-solid.svg`
`center-align-solid.svg`
`check-circle-solid.svg`
`clock-solid.svg`
`cloud-square-solid.svg`
`comp-align-bottom-solid.svg`
`comp-align-left-solid.svg`
`comp-align-right-solid.svg`
`comp-align-top-solid.svg`
`component-solid.svg`
`database-check-solid.svg`
`database-solid.svg`
`database-tag-solid.svg`
`database-xmark-solid.svg`
`design-nib-solid.svg`
`dogecoin-circle-solid.svg`
`download-circle-solid.svg`
`download-square-solid.svg`
`droplet-solid.svg`
`erase-solid.svg`
`ethereum-circle-solid.svg`
`eye-solid.svg`
`fill-color-solid.svg`
`filter-solid.svg`
`forward-solid.svg`
`frame-tool-solid.svg`
`headset-bolt-solid.svg`
`headset-solid.svg`
`headset-warning-solid.svg`
`heart-solid.svg`
`help-circle-solid.svg`
`help-square-solid.svg`
`horiz-distribution-left-solid.svg`
`horiz-distribution-right-solid.svg`
`hospital-circle-solid.svg`
`info-circle-solid.svg`
`italic-square-solid.svg`
`label-solid.svg`
`litecoin-circle-solid.svg`
`medal-solid.svg`
`microphone-check-solid.svg`
`microphone-minus-solid.svg`
`microphone-plus-solid.svg`
`microphone-solid.svg`
`microphone-speaking-solid.svg`
`microphone-warning-solid.svg`
`minus-circle-solid.svg`
`minus-square-solid.svg`
`music-note-plus-solid.svg`
`music-note-solid.svg`
`network-left-solid.svg`
`network-reverse-solid.svg`
`network-right-solid.svg`
`network-solid.svg`
`number-0-square-solid.svg`
`number-1-square-solid.svg`
`number-2-square-solid.svg`
`number-3-square-solid.svg`
`number-4-square-solid.svg`
`number-5-square-solid.svg`
`number-6-square-solid.svg`
`number-7-square-solid.svg`
`number-8-square-solid.svg`
`number-9-square-solid.svg`
`pause-solid.svg`
`percentage-circle-solid.svg`
`percentage-square-solid.svg`
`pin-slash-solid.svg`
`pin-solid.svg`
`play-solid.svg`
`plus-circle-solid.svg`
`plus-square-solid.svg`
`post-solid.svg`
`presentation-solid.svg`
`priority-down-solid.svg`
`priority-high-solid.svg`
`priority-medium-solid.svg`
`priority-up-solid.svg`
`redo-circle-solid.svg`
`refresh-circle-solid.svg`
`reports-solid.svg`
`rewind-solid.svg`
`server-connection-solid.svg`
`server-solid.svg`
`share-android-solid.svg`
`skip-next-solid.svg`
`skip-prev-solid.svg`
`spark-solid.svg`
`sparks-solid.svg`
`square-cursor-solid.svg`
`star-solid.svg`
`stats-down-square-solid.svg`
`stats-up-square-solid.svg`
`style-border-solid.svg`
`text-square-solid.svg`
`three-stars-solid.svg`
`timer-solid.svg`
`trash-solid.svg`
`underline-square-solid.svg`
`undo-circle-solid.svg`
`upload-square-solid.svg`
`usb-solid.svg`
`warning-circle-solid.svg`
`warning-square-solid.svg`
`warning-triangle-solid.svg`
`white-flag-solid.svg`
`wifi-signal-none-solid.svg`
`wifi-tag-solid.svg`
`wifi-warning-solid.svg`
`xmark-circle-solid.svg`
`xmark-square-solid.svg`

**Review by DaniFoldi — APPROVED** [review]
Went through all the icons again, I couldn't find anything in violation of the conventions. Does that mean that all of them are correct? Maybe, but we can start a new list for v8 and rename it in a year.

Amazing work @lucaburgio :tada:

**Comment by lucaburgio** [comment]
Note for release:

Renamed icons by @paescuj 

`1st-medal` to `medal-1st`
`2x2-cell` to `cell-2x2`
`360-view` to `view-360`
`3d-arc-center-pt` to `arc-3d-center-point`
`3d-arc` to `arc-3d`
`3d-bridge` to `bridge-3d`
`3d-center-box` to `box-3d-center`
`3d-draft-face` to `face-3d-draft`
`3d-ellipse-three-pts` to `ellipse-3d-three-points`
`3d-ellipse` to `ellipse-3d`
`3d-pt-box` to `box-3d-point`
`3d-rect-corner-to-corner` to `square-3d-corner-to-corner`
`3d-rect-from-center` to `square-3d-from-center`
`3d-rect-three-pts` to `square-3d-three-points`
`3d-select-edge` to `select-edge-3d`
`3d-select-face` to `select-face-3d`
`3d-select-point` to `select-point-3d`
`3d-three-pts-box` to `box-3d-three-points`
`4k-display` to `display-4k`

**Pull request merged**
